- type: pointOfInterest
  id: BasePOI
  abstract: true
  minimumDistance: 2000 # Some sane defaults
  maximumDistance: 4000
  spawnGamePreset: [ NFAdventure, NFPirate, LuaAdventure ]
  spawnGroup: Optional
  addComponents:
  - type: RadarBlipIcon
    icon: /Textures/_Lua/Interface/Radar/space-outpost.png
    scale: 1.2
    allowWhenHidden: true
  - type: IFF
    color: "#ffa600"
    readOnly: true
  # Prevent gravity changes
  - type: ForceAnchor
